[package]
name = "stub-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-common = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
protocol-macros = { workspace = true }
parking_lot = { workspace = true }
sp-core = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }
tangle-primitives = { workspace = true }
