[package]
name = "ice-frost-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net"] }
gadget-common = { workspace = true }
gadget-core = { workspace = true }
protocol-macros = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
curv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
round-based-21 = { workspace = true, features = ["derive"]}
digest = { workspace = true }
sha2 = { workspace = true }
rand_core = { workspace = true }
rand_chacha = { workspace = true }
aes-gcm = { workspace = true }
zeroize = { workspace = true }
bincode = { workspace = true }

udigest = { workspace = true }
ice-frost = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true, features = ["derive"] }

ark-secp256k1 = { workspace = true }
ark-ed25519 = { workspace = true }


sp-core = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
sp-api = { workspace = true, features = ["std"] }
frame-support = { workspace = true  }
parity-scale-codec = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
parking_lot = { workspace = true }


[dev-dependencies]
test-utils = { workspace = true }
tangle-primitives = { workspace = true }

