[package]
name = "zk-saas-protocol"
version = "0.1.0"
edition = "2021"

[features]

parallel = [
    "ark-std/parallel",
    # "groth16/parallel",
    "rayon"
]

[dependencies]
protocol-macros = { workspace = true }
gadget-common = { workspace = true }
tokio-rustls = { workspace = true }
mpc-net = { workspace = true }
secret-sharing = { workspace = true }
dist-primitives = { workspace = true }
groth16 = { workspace = true }
gadget-core = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
fflonk = { git = "https://github.com/w3f/fflonk", features = ["std"] }
futures = { workspace = true }


sp-runtime = { workspace = true }
sp-core = { workspace = true }
tangle-primitives = { workspace = true, features = ["verifying"] }

ark-serialize = { workspace = true, default-features = false }
ark-groth16 = { workspace = true, default-features = false }
ark-poly = { workspace = true, default-features = false }
ark-relations = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
ark-crypto-primitives = { workspace = true, default-features = false }
ark-ff = { workspace = true, default-features = false }
ark-circom = { workspace = true }


ark-bn254 = { workspace = true, default-features = false, features = ["curve"] }
rayon = { workspace = true, optional = true }

[dev-dependencies]
ark-std = { workspace = true, default-features = false }
frame-support = { workspace = true }
test-utils = { workspace = true }
rcgen = "0.12.0"
gadget-common = { workspace = true, features = ["testing"] }
